version: '1.0'

services:
   mysqldb:
     image: mysql:5.6
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: bootexample
       MYSQL_USER: mysql
       MYSQL_PASSWORD: password
     ports:
       -"3306:3306"

   springboot:
     depends_on:
       - mysqldb
     image: wipasp/spring-mysql
     links:
     - mysqldb
     ports:
       - "8090:8090"
     restart: always