version: '2.2'

services:
   mysqldb:
     image: mysql:5.6
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: bootexample
       MYSQL_USER: mysql
       MYSQL_PASSWORD: password
     ports:
       - "3306"
     networks:
       - internalnet

   springboot:
     depends_on:
       - mysqldb
     image: wipasp/spring-mysql
     links:
     - mysqldb
     ports:
       - "8090"
     networks:
       - internalnet

networks:
  internalnet: 
